package com.worldmind.core.model;

import java.io.Serializable;
import java.util.List;

/**
 * Clarifying questions generated by the LLM to gather more context
 * before creating the detailed PRD. These are presented to the user
 * for answers before spec generation proceeds.
 */
public record ClarifyingQuestions(
    List<Question> questions,
    String summary  // Brief summary of what the system understood
) implements Serializable {

    /**
     * A single clarifying question with options or free-form input.
     */
    public record Question(
        String id,
        String question,
        String category,       // "scope", "technical", "ux", "integration", "constraints"
        String whyAsking,      // Explains why this matters for the implementation
        List<String> suggestedOptions,  // Optional pre-defined choices
        boolean required,      // Must be answered before proceeding
        String defaultAnswer   // Optional default if user skips
    ) implements Serializable {}
}
