package com.worldmind.core.model;

import java.io.Serializable;
import java.util.List;

/**
 * Structured product specification generated by the LLM before mission planning.
 * Written to the project directory as SPEC.md and used by the planner to produce
 * focused, well-scoped directives.
 */
public record ProductSpec(
    String title,
    String overview,
    List<String> goals,
    List<String> nonGoals,
    List<String> technicalRequirements,
    List<String> acceptanceCriteria,
    List<ComponentSpec> components,
    List<String> edgeCases,
    List<String> outOfScopeAssumptions
) implements Serializable {

    public record ComponentSpec(
        String name,
        String responsibility,
        List<String> affectedFiles,
        List<String> behaviorExpectations,
        List<String> integrationPoints
    ) implements Serializable {}
}
