package com.worldmind.core.model;

import java.io.Serializable;
import java.util.List;

/**
 * Detailed Product Requirements Document (PRD) generated by the LLM before mission planning.
 * Written to the project directory as SPEC.md and used by the planner to produce
 * focused, well-scoped directives with implementation-ready detail.
 */
public record ProductSpec(
    String title,
    String overview,
    List<String> goals,
    List<String> nonGoals,
    List<String> technicalRequirements,
    List<String> acceptanceCriteria,
    List<ComponentSpec> components,
    List<String> edgeCases,
    List<String> outOfScopeAssumptions
    // Note: Enhanced PRD fields (implementationPlan, fileSpecs, userExperience) 
    // temporarily removed due to Spring AI BeanOutputConverter parsing issues with 
    // deeply nested records. The core spec fields above are sufficient for planning.
) implements Serializable {

    public record ComponentSpec(
        String name,
        String responsibility,
        List<String> affectedFiles,
        List<String> behaviorExpectations,
        List<String> integrationPoints
    ) implements Serializable {}
    
    /**
     * Step-by-step implementation plan with specific tasks.
     */
    public record ImplementationPlan(
        List<ImplementationStep> steps,
        String suggestedOrder,
        List<String> parallelizableGroups
    ) implements Serializable {}
    
    /**
     * A single implementation step with detailed instructions.
     */
    public record ImplementationStep(
        String stepNumber,
        String title,
        String description,
        List<String> filesInvolved,
        List<String> detailedTasks,
        List<String> dependencies,
        String verificationMethod
    ) implements Serializable {}
    
    /**
     * Specification for a file to be created or modified.
     */
    public record FileSpec(
        String filePath,
        String purpose,
        List<String> mustContain,
        List<String> mustNotContain,
        String templateOrStructure
    ) implements Serializable {}
    
    /**
     * User experience requirements for visual/interactive applications.
     */
    public record UserExperience(
        String visualStyle,
        List<String> interactions,
        List<String> animations,
        String colorScheme,
        List<String> accessibilityRequirements
    ) implements Serializable {}
}
